### ISSUE TITLE
Make https://why-upgrade.depesz.com/ working

### ISSUE THREAD

**Issue by tigerfoot** [depesz/pgVersions#3]
Thanks for this over cool tools.
Would it be possible to make also https working. Actually there's a certifcate error (api.pgxn.org)

**Comment by depesz** [comment]
well, for now it's not available over https. will add https there, but not this week, sorry.

**Comment by tigerfoot** [comment]
There's no emergency, this just serve as kind reminder ;-)

**Comment by depesz** [comment]
https added
